### ISSUE TITLE
Flathub app is "unverified"

### ISSUE THREAD

**Issue by kelson42** [kiwix/operations#338]
This is not optimal to gain trust from users!

<img width="1080" alt="Image" src="https://github.com/user-attachments/assets/03de1e53-1398-4487-9f0c-7f30b437ba27" />

**Comment by kelson42** [comment]
@rgaudin we need to make a well-known file on kiwix.org Wordpress and this has to be done by someone which has the permission on the kiwix flathib repository. On my side, not sire how to create the well-known file.

**Comment by rgaudin** [comment]
Done

```sh
❯ curl https://kiwix.org/.well-known/org.flathub.VerifiedApps.txt
4e5671c2-2415-4f0a-8e8d-ee0eaf27521c
```

**Comment by kelson42** [comment]
@rgaudin Thank you, for the moment it still show "unverified" on the page although the technical part looks good. Hopefully this is only a cache problem.

**Comment by rgaudin** [comment]
I believe we have to re-request verification but I dont have the flathub credentials

**Comment by kelson42** [comment]
> I believe we have to re-request verification but I dont have the flathub credentials

From want I understand from my case, if you connect via GitHub you should have all the needed permission.

**Comment by kelson42** [comment]
@rgaudin Looks good now!
![Image](https://github.com/user-attachments/assets/321ab9c0-f9c0-40d0-a2be-5717c390e40f)
